### ISSUE TITLE
Issue with Midi-qol damage rolls

### ISSUE THREAD

**Issue by cadowtin** [kaelad02/adv-reminder#22] opened 2022-02-07 12:04 UTC
When using midi-qol, unable to roll damage, as it gives the following error.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shiftKey')
[Detected 4 packages: adv-reminder, lib-wrapper, more-hooks-5e, midi-qol]
    at isFastForwarding (modules/adv-reminder/src/module.js:269)
    at isFastForwardingDamage (modules/adv-reminder/src/module.js:286)
    at Item5e.onRollDamage (modules/adv-reminder/src/module.js:244)
    at Wrapper.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1)
    at Item5e.rollDamagePatch (modules/more-hooks-5e/scripts/item/damageRoll.js:8)
    at Wrapper.🎁call_wrapper [as call_wrapper] (modules/lib-wrapper/lib-wrapper.js:1)
    at Item5e.🎁CONFIG.Item.documentClass.prototype.rollDamage#0 (modules/lib-wrapper/lib-wrapper.js:1)
    at Workflow._next (modules/midi-qol/src/module/workflow.js:472)
    at async Workflow.next (modules/midi-qol/src/module/workflow.js:245)
```

**Comment by kaelad02** [comment] 2022-02-07 21:30
I can't reproduce the issue. I might just put something in anyways, but what version of Foundry and Midi-QOL are you using?

**Comment by kaelad02** [comment] 2022-02-07 21:35
I can only reproduce it from a macro and don't need Midi for that. The code below will reproduce it and removing `event: null` will make the roll work.
```javascript
const item = actor.items.getName("Greataxe");
await item.rollDamage({ event: null });
```
Are you triggering it from a macro maybe?

**Comment by cadowtin** [comment] 2022-02-08 01:13
- Foundry V. 9.249,
- Midi QOL v 0.9.08

And it seems to apply to actors that don't even have any flags on them?

**Comment by cadowtin** [comment] 2022-02-08 01:27
Okay It looks like I can roll damage on it's own. But if I have it setup as follows (I think the auto fast forward damage) is causing all issues.
![image](https://user-images.githubusercontent.com/79132112/152900405-442b9442-97a8-4634-8011-ed7a193f5258.png)

**Comment by cadowtin** [comment] 2022-02-08 04:42
I believe it seems to be related to the midi-qol workflow?

But no I have tested it using SRD items built in to foundry rolling them normally.

**Comment by kaelad02** [comment] 2022-02-08 04:44
For some reason midi's passing a null `event`. I'm taking a look at its code to confirm and see why.

**Comment by kaelad02** [comment] 2022-02-08 05:11
It is a regression in midi when you auto-roll damage. If you change midi's settings so it doesn't auto-roll damage it won't happen. I'll file an issue w/ midi but I'll put something in here anyways.

Using version 0.8.85 it does not happen but 0.9.08 it does. For some reason, it's now passing `event = null` in the roll options to the damage roll where it was missing from roll options before. Passing it as `null` is causing the problem.

**Comment by cadowtin** [comment] 2022-02-08 05:38
Cool, thank you for the response, hopefully it gets resolved.

**Comment by kaelad02** [comment] 2022-02-08 05:45
Filed the issue and I'll get a fix for this module now and push that out in the meantime.

https://gitlab.com/tposney/midi-qol/-/issues/686

**Closed** 2022-02-08 05:58 UTC
Labels: bug

**Comment by kaelad02** [comment] 2022-02-08 06:01
version 1.2 is live with this bug fix

**Comment by cadowtin** [comment] 2022-02-09 09:53
ty ty, i see it, hopefully midi qol fixes the compatibility issue
